### ISSUE TITLE
is that possible to convert and using onnx file?

### ISSUE THREAD

**Issue by MinGiSa** [nachifur/automatic-label-correction-CCEDD#7]
Thank you for sharing your works.
I've been looking for materials related to edge detection, 
and this GitHub repository seems like a great resource.
By the way, is it possible to convert the model file to ONNX format for inference and use it?

It seems like some time has passed since you opend this github, but I'll wait for your response.

**Comment by nachifur** [comment]
Our codes are based on pytorch.

See pytoch->ONNX:

https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html.

**Comment by MinGiSa** [comment]
thanks a lot!

> Our codes are based on pytorch.
> 
> See pytoch->ONNX:
> 
> https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html.
